"""Add work_issue is_resolved.

Revision ID: 3c4808ad717a
Revises: af4022c1a70c
Create Date: 2024-11-18 00:26:58.298073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c4808ad717a'
down_revision = 'af4022c1a70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('work_issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_resolved', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('work_issues_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_resolved', sa.Boolean(), autoincrement=False, nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_issues_history', schema=None) as batch_op:
        batch_op.drop_column('is_resolved')

    with op.batch_alter_table('work_issues', schema=None) as batch_op:
        batch_op.drop_column('is_resolved')

    # ### end Alembic commands ###
